links:
  rails:
    tutorial: "https://www.railstutorial.org/"
    home: "https://rubyonrails.org/"
    help: "https://www.railstutorial.org/help"
    contact: "https://www.railstutorial.org/contact"
    book: "https://www.railstutorial.org/book"
    news: "https://news.railstutorial.org/"
    screencasts: "https://screencasts.railstutorial.org/"
  others:
    michaelhartl: "https://www.michaelhartl.com/"
    learn_enough: "https://www.learnenough.com/"
    gravatar: "https://gravatar.com/emails"
user_name:
  max_length: 50
email:
  max_length: 255
password:
  min_length: 6
micropost:
  max_length: 140
  type: "image/jpeg image/gif image/png"
  view_type: "image/jpeg, image/gif, image/png"
  img_limit: 500
page: 5
ava:
  size: 80
  small_size: 30
user:
  size: 50
